### ISSUE TITLE
App crash at start

### ISSUE THREAD

**Issue by rohitjakhar** [tmehta813/catdetails#1]
Steps:
1. clone repo
2. paste cat api key
3. run project
crash.

log:
```
FATAL EXCEPTION: main
                                                                                                    Process: com.sample.catapp, PID: 19659
                                                                                                    java.lang.RuntimeException: Unable to instantiate application com.sample.catapp.IntuitSampleApp package com.sample.catapp: java.lang.ClassNotFoundException: Didn't find class "com.sample.catapp.IntuitSampleApp" on path: DexPathList[[zip file "/data/app/~~NOKoJr1lxmQUNM3BEQ46lg==/com.sample.catapp--RnXrDBQBHe0VS1qRWgv9w==/base.apk"],nativeLibraryDirectories=[/data/app/~~NOKoJr1lxmQUNM3BEQ46lg==/com.sample.catapp--RnXrDBQBHe0VS1qRWgv9w==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1485)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1414)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6888)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2219)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:238)
                                                                                                    	at android.os.Looper.loop(Looper.java:357)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8088)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sample.catapp.IntuitSampleApp" on path: DexPathList[[zip file "/data/app/~~NOKoJr1lxmQUNM3BEQ46lg==/com.sample.catapp--RnXrDBQBHe0VS1qRWgv9w==/base.apk"],nativeLibraryDirectories=[/data/app/~~NOKoJr1lxmQUNM3BEQ46lg==/com.sample.catapp--RnXrDBQBHe0VS1qRWgv9w==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:51)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1234)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1477)
                                                                                                    	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1414) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6888) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2219) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:238) 
                                                                                                    	at android.os.Looper.loop(Looper.java:357) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8088) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957) 
                                                                                                    
```

**Comment by tmehta813** [comment]
fixed
